# Generated by Django 6.1.1 on 2026-09-17 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_ticket_options_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={"ordering": ["departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["distance"]},
        ),
    ]
