# Generated by Django 6.1.1 on 2026-09-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_airplane_options_alter_airplanetype_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("destination")), _negated=True),
                name="source_different_from_destination",
            ),
        ),
    ]
