# Generated by Django 6.1.1 on 2026-09-18 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_route_source_different_from_destination"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="airport",
            constraint=models.CheckConstraint(
                condition=models.Q(("closest_big_city__regex", "^[A-Za-z ]+$")),
                name="closest_big_city must have only letters",
            ),
        ),
    ]
