# Generated by Django 6.1.1 on 2026-09-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_airport_closest_big_city_must_have_only_letters"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
